/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_anative_Test */

#ifndef _Included_com_example_anative_Test
#define _Included_com_example_anative_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anative_Test
 * Method:    testaaa
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anative_Test_testaaa
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
