/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_anative_NativeColorRenderer_Companion */

#ifndef _Included_com_example_anative_NativeColorRenderer_Companion
#define _Included_com_example_anative_NativeColorRenderer_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
