/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_anative_NativeColorRenderer */

#ifndef _Included_com_example_anative_NativeColorRenderer
#define _Included_com_example_anative_NativeColorRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anative_NativeColorRenderer
 * Method:    surfaceCreate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_anative_NativeColorRenderer_surfaceCreate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_anative_NativeColorRenderer
 * Method:    surfaceChange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_anative_NativeColorRenderer_surfaceChange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_anative_NativeColorRenderer
 * Method:    drawFrame
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;)V
 */
JNIEXPORT void JNICALL Java_com_example_anative_NativeColorRenderer_drawFrame
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
